spring.application.name=practice

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER_CLASS}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=PostgreSQL
spring.jpa.show-sql=true


spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

spring.cache.type=jcache
logging.level.org.springframework.cache=DEBUG
logging.level.org.springframework.cache.interceptor=TRACE


spring.cache.jcache.config=classpath:ehcache.xml
spring.jpa.properties.hibernate.cache.use_second_level_cache=true
spring.jpa.properties.hibernate.cache.use_query_cache=true
spring.jpa.properties.hibernate.cache.region.factory_class=org.hibernate.cache.jcache.JCacheRegionFactory
spring.jpa.properties.hibernate.cache.jcache.config=classpath:ehcache.xml